#!/usr/bin/env bash

echo "======================================"
echo "⚠️  此脚本已弃用"
echo "======================================"
echo ""
echo "请使用新的发布脚本："
echo ""
echo "  在项目根目录运行："
echo "  $ pnpm release"
echo ""
echo "  或直接运行："
echo "  $ bash release.sh"
echo ""
echo "新脚本提供了更完善的发布流程："
echo "  ✓ 完整的发布前检查"
echo "  ✓ 测试和代码质量检查"
echo "  ✓ 构建产物验证"
echo "  ✓ Git 标签管理"
echo "  ✓ 错误处理和回滚"
echo ""
echo "======================================"
echo ""

exit 1
