export { default } from './index.vue'
export { default as FStep } from './FStep.vue'
export type { StepsProps, StepsProvideValue } from './Steps'
export { stepsPropsKey } from './Steps'
export type { StepProps } from './FStep.vue'
