name: CI
on:
  push:
    branches: [ master ] // github默认分支是main,我这里是master
  pull_request:
    branches: [ master ] // github默认分支是main,我这里是master
jobs:
  # Lint:
    # Lint任务
  UnitTest:
   # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Install modules
        run: cd packages/fit-ui && pnpm install
      - name: Run Test
        run: cd packages/fit-ui && pnpm run test:run
